### ISSUE TITLE
Counters with value of 0 are non-intuitive

### ISSUE THREAD

**Issue by adamlamore** [Fugiman/kaet#16]
If you use "reset" the output says "0" but the counter is actually gone (and no longer available in commands). If you want a live counter with a value of 0 you have to create the counter with "inc"/"dec" and then use those commands to get the value to 0 (e.g. create a new counter with "inc" and "dec" back to 0). Perhaps "reset" and "removecounter" should be separate commands?

**Comment by adamlamore** [comment]
In order to not add yet another command, you could also make "reset" not remove the counter and instead modify "removecommand" to handle counters as well.

**Comment by FugiTech** [comment]
This is by design, and honestly I may make decrementing a counter to zero remove it as well. I can't see a good use-case for zero counters.

**Comment by adamlamore** [comment]
One example: "!chicken" for counting PUBG wins. Mod resets to 0 at start of stream. Allows newly arrived viewers to find out without bothering anyone.
