### ISSUE TITLE
Streamer should count as a mod

### ISSUE THREAD

**Issue by r4v5** [Fugiman/kaet#9]
It doesn't seem like the streamer counts as a 'mod' for purpose of 'mod-only commands', meaning streamer can't easily create/delete their own commands.

Example debug output, showing the user-type being empty:
> 2017/07/24 16:52:36 [IN]  @badges=moderator/1,subscriber/0,turbo/1;color=#5F5775;display-name=r4v5;emotes=433:65-66;id=156a2dbc-ff2f-404e-99fb-4abc589a2204;mod=1;room-id=113481237;subscriber=1;tmi-sent-ts=1500933155182;turbo=1;user-id=39399416;user-type=mod :r4v5!r4v5@r4v5.tmi.twitch.tv PRIVMSG #bengineering :Yep, still need to fix that so that the streamer counts as a mod
> 2017/07/24 16:52:51 [IN]  @badges=broadcaster/1,subscriber/0;color=#DAA520;display-name=Bengineering;emotes=;id=c25b5f41-5884-48ff-b638-b9a58baba0ee;mod=0;room-id=113481237;sent-ts=1500933126760;subscriber=1;tmi-sent-ts=1500933170337;turbo=0;user-id=113481237;user-type= :bengineering!bengineering@bengineering.tmi.twitch.tv PRIVMSG #bengineering :ohhhh alright cool I thought I was crazy

**Comment by rakslice** [comment]
Workaround: Streamer can mod themselves in Twitch chat with the `/mod` command :D
